version: "3.6"
services:
  ethstats:
    image: ghcr.io/noku-team/ethstats-server-poa:latest
    environment: 
      NETWORK: noku
    restart: always
    ports:
      - "80:3000/tcp"
    env_file:
      - .env.stats.dashboard