name: Build Network
on:
  workflow_dispatch:
    inputs:
      network:
        type: choice
        description: Choose a Network
        options:
          - nokuchain
          - 3achain
          - luxochain
jobs:
  build-network:
    uses: noku-team/ethstats-server-poa/.github/workflows/build.yml@master
    with:
      network: ${{inputs.network}}
      registry_endpoint: "ghcr.io"
